### PR TITLE
Update average intensity with latest data

### PR DESCRIPTION
**Pull request by fershad**
This PR updates the average Grid Intensity data in CO2.js with the latest available data from Ember. It changes a few things:

- 🤖 Fetches data from Ember's data API, rather than relying on us having to manually download & manipulate a CSV file.
- 📆 It returns the latest available data for _all_ countries/regions in the Ember dataset rather than the most recent calendar year.
  - 💡 This means we now have average availability data for 221 countries
  - ⚠️ Some countries don't have emissions data for the last few years (Reunion for example last reported in 2011 - in this case, we return the 2011 data)
- 🤖 Removes the year suffix on the filename. This paves the way for automating the update process, so that it can be run periodically through a Github action.

### CODE REVIEW

**Comment by fershad** [comment]
I've also fixed an error with the marginal intensity code that was causing the `npm run intensity-data` command to fail.

**Comment by fershad** [comment]
LOL of course this would cause tests to fail, since the average intensity data used in some of them is not out of sync. Definitely need to work out how to make the tests more robust/introduce an acceptable margin of error before automating data updates.

**Comment by fershad** [comment]
[Update grid intensity data for 2022 in CO2.js](https://trello.com/c/YdEuwOCh/114-update-grid-intensity-data-for-2022-in-co2js)

**Comment by mrchrisadams** [comment]
Hey fish, i'm happy to merge this in.

**Pull request merged**
