### PR TITLE
refactor(typescript): refactored code to use typescript

### PR DESCRIPTION
**Pull request by dvelasquez**
This PR refactors the code to use TypeScript instead of VanillaJS.

## Changes
* Updated eslint to handle typescript code
* Refactored source files to typescript
* Refactored test files to typescript
* Fixed some issues with the tests
* Updated package.json to expose CJS and ES Modules
* Created Type Definition for the PageXRay module

### CODE REVIEW

**Comment by mrchrisadams** [comment]
HI @dvelasquez, I've had a chance to look over this, and I really like it - thanks for taking the time to work on it.

I'd like to merge this in with fresh eyes though, so I'm going to check tomorrow to see what changes might be needed in code that consumes the earlier released version of co2.js, then then, and update the changelog and README, to prep for a new release. 

Much gracias 👍

**Comment by dvelasquez** [comment]
Hey! It would be really interesting to try this branch with a project that uses this as a dependency, to check if everything is ok

**Comment by mrchrisadams** [comment]
Indeed!

Sitespeed would be the big one, as it's in production in a few high profile places. Here's an example of their public dashboards:

Screenshot 2020-10-02 at 18 22 22

And below is the direct link to the chart:

https://dashboard.sitespeed.io/d/000000060/leaderboard?orgId=1&from=1603728284785&to=1604333084785&var-namespace=sitespeed_io&var-path=alexaDesktop&var-domains=All&var-pages=All&var-browser=chrome&var-connectivity=cable&var-function=median&viewPanel=79

I had planned to:

-  a checkout of sitespeed
- update the dependencies to point to this branch
- run the tests and see if we get the numbers

This here where it's in use in the sitespeed codebase:

https://github.com/sitespeedio/sitespeed.io/blob/main/lib/plugins/sustainable/index.js#L8-L13

And the tests looked like this, but they've since been moved into a separate repo:

https://github.com/sitespeedio/sitespeed.io/pull/2868/files

**Review by drydenwilliams — APPROVED** [review]
Looks pretty great to me 👍 

**note**: haven't run it locally

**Pull request closed without merging**
