### PR TITLE
Create contributing.md

### PR DESCRIPTION
**Pull request by fershad**
This PR adds the following new files to this project repository.

- CONTRIBUTING.md
- CODE_OF_CONDUCT.md

This addresses #165

### CODE REVIEW

**Comment by fershad** [comment]
@mrchrisadams could you review the contents of both documents & let me know if any changes are required before merging.

**Comment by mrchrisadams** [comment]
Thanks for this @fershad  - this appears to be based on the 1.4 version of the contributor covenant, and there's new version out - was there a deliberate decision to choose the 1.4 variant?

https://www.contributor-covenant.org/version/2/1/code_of_conduct/

I've looked over 2.1, and I'm comfortable with us using that as the main differences I see seem to be more clarity about escalation, and not being so specific about contact channel (1.4 says [INSERT EMAIL ADDRESS], and 2.1 says [INSERT CONTACT METHOD])

**Escalation path**

Also, this bit here:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at [INSERT EMAIL ADDRESS].

I think we'll need to add an email address in the CoC.

It took me about a minute to set up code_of_conduct@thegreenwebfoundation.org, which we can use, and for the time being I've set this up to send messages to me, as I work full time for the foundation, and at least that way there's a clear escalation path.

Finally, before we merge this in, can you please take a few minutes to see if it makes sense  to create these docs at the root level of the org, so it cascades through all our projects? I think github supports defining a document or template at the organisational level, which then becomes the default for all projects, but I've never implemented it before myself.

**Review by mrchrisadams — APPROVED** [review]
hey Fish, I have a couple of questions that I think should be fast to understand and answer before we merge this in, but directionally this is good.

Once you've answered them, or addressed the feedback, I'm happy for you to merge this PR. If it turns there are other changes needed, I'll make an issue or PR myself.

**Comment by fershad** [comment]
Thanks @mrchrisadams. I've found out how to create organisation wide defaults for Code of Conduct, Contribution & Funding. https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

We can override these in individual repos as required, but for now I'll use the content of these documents (updated Code of Conduct to 2.1) for the org-wide defaults.

**Comment by fershad** [comment]
Files created for organisation in https://github.com/thegreenwebfoundation/.github

**Pull request closed without merging**
