### PR TITLE
Merge v0.10.0 work back into main 

### PR DESCRIPTION
**Pull request by mrchrisadams**
This PR brings back the work carried out with @fershad to improve the developer experience and documentation for using CO2.js.

This includes:

- [x] switching to import syntax from commonjs syntax in the `src` directory
- [x] making this a hybrid module for using in server side and clientside browser runtimes
- [x] updated docs for first use
- [x] decide whether to update defaults to use the SWD model not the 1ybte model for carbon calculation, and add warnings
- [x] Add links to spreadsheet calcs in documentation, after sanity checking the workings one last time

### CODE REVIEW

**Comment by fershad** [comment]
@mrchrisadams should we output the IIFE version to the `/dist` folder as well (currently gets built to `/public`). In this way we can document how people can build the library from source & point them to a single output location with all three versions.

**Comment by fershad** [comment]
I've created a GitPod configuration file for the project. This builds the different versions & opens the demo in the `/public` folder when the repo is launched in GitPod.

**Comment by mrchrisadams** [comment]
[Release CO2.js 0.10.x](https://trello.com/c/W4THYab8/29-release-co2js-010x)

**Comment by mrchrisadams** [comment]
Sup @fershad 

> should we output the IIFE version to the /dist folder as well (currently gets built to /public). In this way we can document how people can build the library from source & point them to a single output location with all three versions.

I think this is a good idea. I had initially thought that it made sense to copy of the iife version it from `/dist` to `/public`, so that people could serve just files in the `public` folder by itself.

But if it's not necessary to do that I'm happy to refer to the iife in `dist`.

### Splitting out the other parts of the project

There are two other items in this PR to be completed:

- updated docs for first use
- decide whether to update defaults to use the SWD model not the 1ybte model for carbon calculation, and add warnings

Because we already have another inbound PR for updated documentation, and because the shift to the SWD model likely changes some resulting carbon calculations, I'm happy to split these both out. so we can get 0.10.0 published to npm and merged back into main.

**Comment by fershad** [comment]
> Oh @fershad - if you do, can you please move the issue about switching the default calculation model to the next milestone, so I know to get the dev work lined up for them?
> 
> https://github.com/thegreenwebfoundation/co2.js/milestone/3

I've moved that to the 0.11.0 milestone.

**Comment by fershad** [comment]
Thanks @mrchrisadams
I'll add a small update to the README in this PR to point to the docs site.

**Comment by mrchrisadams** [comment]
Actually @fershad  - there's one check we need to make on this before we merge in. I want to sanity check the calcs against a spreadsheet, and document how to do the same, so others can do so as well.

**Comment by mrchrisadams** [comment]
OK, I've resolved the discrepancies here between the code and the spreadsheet. It was a by product of CO2.js using rounded numbers, and the spreadsheet _not_ using the rounded figures. Merging in.

**Pull request merged**
