### PR TITLE
Add marginal carbon intensity data from UNFCCC

### PR DESCRIPTION
**Pull request by fershad**
This PR adds country level marginal carbon intensity data from the UNFCCC to CO2.js. Initially (in this PR) we will be including the source data, and introducing scripts to generate JSON and JS exports of the source CSV file. 

Todo:

- [x] ISO 2 & 3 letter country code mapping
- [ ] Figure out how to handle memo notes that appear at the end of the dataset (e.g. [Memo: EU 27](https://github.com/thegreenwebfoundation/co2.js/compare/fi-add-unfccc-marginal-intensity-numbers?expand=1#diff-4dffc28484e4e23e6d865d922a6865e85c714ee51888e5e509aa89d02e89eb9bR239))
- [ ] Figure out how to handle countries that have all 0s ([example](https://github.com/thegreenwebfoundation/co2.js/compare/fi-add-unfccc-marginal-intensity-numbers?expand=1#diff-4dffc28484e4e23e6d865d922a6865e85c714ee51888e5e509aa89d02e89eb9bR7))

### CODE REVIEW

**Comment by fershad** [comment]
[Include EMBER and UNFCCC data in CO2.js](https://trello.com/c/vcBJO5ig/69-include-ember-and-unfccc-data-in-co2js)

**Comment by fershad** [comment]
@mrchrisadams This PR is ready for review. It exposes the UNFCCC data in JSON format, just like we have done for Ember in #69. In order to do this, I have:

1. Added the UNFCCC data as a CSV file in `data/IFI_Default_Grid_Factors_2021_v3.1_unfccc.csv`
2. Added a new column in the `countries.csv` file to allow the UNFCCC country names to also be mapped to country codes ([diff](https://github.com/thegreenwebfoundation/co2.js/pull/102/files#diff-b3434d2b60e2b4e9acb345413290c59cd9e49fa1c9af6f207e7f7d452ed403f6))
    - Please note that some countries in the Ember data are not in the UNFCCC data (e.g. Hong Kong), and some in the UNFCCC data are not in Ember (e.g. Tuvalu).
    - I have also added regions from the two datasets, although we don't use them at the moment.
 3. Moved more of the code into common utils functions which should be easier to maintain going forward.
 4. Moved the main generator scripts into a `functions` folder to keep the main `data` folder clean.
 5. Added scripts for marginal intensity to the `package.json`.

**Comment by fershad** [comment]
@mrchrisadams this should be all set now with the changes we discussed yesterday for #104

**Review by mrchrisadams — APPROVED** [review]
hi @fershad  I'm happy for this to be merged in.

Thanks for putting the work in.

There are a lot of commits in this PR, and it doesn't look like we can rebase these in. I'm happy with a squash commit if it makes it easier to get this into the main branch, for us to start thinking about how to use this data in an extended API.

**Pull request merged**
