### PR TITLE
Read JSON blob also as gzipped.

### PR DESCRIPTION
**Pull request by soulgalore**
Adding logic to read the JSON file when its gzipped. Couldn't test this though since it depends on url2green that needs NodeJS 14 (see my other PR) so its made blindly ... so let me test it when the other package is updated :)

### CODE REVIEW

**Comment by soulgalore** [comment]
I renamed the database and updated the dependencies but the tests against the remote API fails, it receives empty arrays. Do you know @mrchrisadams if something changed over time?

**Comment by mrchrisadams** [comment]
Hi @soulgalore. 

Yes, a while back we made some changes to the multi-check and this morning when fixing the tests, I realised I needed to push an update to the API too. The tests should be passing again here (I didn't see your change to the database fixture until just now - thank you btw)

**Comment by mrchrisadams** [comment]
I think all this needs now is the `data/fixtures/url2green.test.db` file to be removed, as I made the same name change when fixing the tests this morning.

Thanks again for the gzip option - I didn't know it was part of node core. Given the renewed interest in the datasets, I think I might make this endpoint more machine readable, so it's easy to fetch a compress local copy. I've made an issue below to capture discussion in the meantime.

https://github.com/thegreenwebfoundation/co2.js/issues/47

**Comment by soulgalore** [comment]
@mrchrisadams is this good to go now? Also it seems that 0.7 wasn't released to npm (can also see it in the changelog), could this be released as 0.8, wanna change how we use it in sitespeed.io.

**Pull request merged**
